package shuaihu.vip.mbg.pojo;

public class Dept {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEPT.DEPT_ID
     *
     * @mbggenerated Tue Feb 14 17:37:40 CST 2023
     */
    private Integer deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEPT.DEPT_NAME
     *
     * @mbggenerated Tue Feb 14 17:37:40 CST 2023
     */
    private String deptName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEPT.DEPT_ID
     *
     * @return the value of T_DEPT.DEPT_ID
     *
     * @mbggenerated Tue Feb 14 17:37:40 CST 2023
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEPT.DEPT_ID
     *
     * @param deptId the value for T_DEPT.DEPT_ID
     *
     * @mbggenerated Tue Feb 14 17:37:40 CST 2023
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEPT.DEPT_NAME
     *
     * @return the value of T_DEPT.DEPT_NAME
     *
     * @mbggenerated Tue Feb 14 17:37:40 CST 2023
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEPT.DEPT_NAME
     *
     * @param deptName the value for T_DEPT.DEPT_NAME
     *
     * @mbggenerated Tue Feb 14 17:37:40 CST 2023
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    @Override
    public String toString() {
        return "Dept{" +
                "deptId=" + deptId +
                ", deptName='" + deptName + '\'' +
                '}';
    }
}