package shuaihu.vip.mbg.pojo;

public class Post {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.name
     *
     * @mbggenerated Tue Feb 14 17:37:40 CST 2023
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.content
     *
     * @mbggenerated Tue Feb 14 17:37:40 CST 2023
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.name
     *
     * @return the value of post.name
     *
     * @mbggenerated Tue Feb 14 17:37:40 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.name
     *
     * @param name the value for post.name
     *
     * @mbggenerated Tue Feb 14 17:37:40 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.content
     *
     * @return the value of post.content
     *
     * @mbggenerated Tue Feb 14 17:37:40 CST 2023
     */
    public String getContent() {
        return content;
    }

    public Post(String name, String content) {
        this.name = name;
        this.content = content;
    }

    public Post() {
    }

    @Override
    public String toString() {
        return "Post{" +
                "name='" + name + '\'' +
                ", content='" + content + '\'' +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.content
     *
     * @param content the value for post.content
     *
     * @mbggenerated Tue Feb 14 17:37:40 CST 2023
     */

    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}