package shuaihu.vip.mbg.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import shuaihu.vip.mbg.pojo.Dept;
import shuaihu.vip.mbg.pojo.DeptExample;

public interface DeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEPT
     *
     * @mbggenerated Tue Feb 14 17:37:40 CST 2023
     */
    int countByExample(DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEPT
     *
     * @mbggenerated Tue Feb 14 17:37:40 CST 2023
     */
    int deleteByExample(DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEPT
     *
     * @mbggenerated Tue Feb 14 17:37:40 CST 2023
     */
    int deleteByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEPT
     *
     * @mbggenerated Tue Feb 14 17:37:40 CST 2023
     */
    int insert(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEPT
     *
     * @mbggenerated Tue Feb 14 17:37:40 CST 2023
     */
    int insertSelective(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEPT
     *
     * @mbggenerated Tue Feb 14 17:37:40 CST 2023
     */
    List<Dept> selectByExample(DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEPT
     *
     * @mbggenerated Tue Feb 14 17:37:40 CST 2023
     */
    Dept selectByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEPT
     *
     * @mbggenerated Tue Feb 14 17:37:40 CST 2023
     */
    int updateByExampleSelective(@Param("record") Dept record, @Param("example") DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEPT
     *
     * @mbggenerated Tue Feb 14 17:37:40 CST 2023
     */
    int updateByExample(@Param("record") Dept record, @Param("example") DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEPT
     *
     * @mbggenerated Tue Feb 14 17:37:40 CST 2023
     */
    int updateByPrimaryKeySelective(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DEPT
     *
     * @mbggenerated Tue Feb 14 17:37:40 CST 2023
     */
    int updateByPrimaryKey(Dept record);
}