package shuaihu.vip.mbg.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import shuaihu.vip.mbg.pojo.Post;
import shuaihu.vip.mbg.pojo.PostExample;

public interface PostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated Tue Feb 14 17:37:40 CST 2023
     */
    int countByExample(PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated Tue Feb 14 17:37:40 CST 2023
     */
    int deleteByExample(PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated Tue Feb 14 17:37:40 CST 2023
     */
    int insert(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated Tue Feb 14 17:37:40 CST 2023
     */
    int insertSelective(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated Tue Feb 14 17:37:40 CST 2023
     */
    List<Post> selectByExample(PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated Tue Feb 14 17:37:40 CST 2023
     */
    int updateByExampleSelective(@Param("record") Post record, @Param("example") PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated Tue Feb 14 17:37:40 CST 2023
     */
    int updateByExample(@Param("record") Post record, @Param("example") PostExample example);
}